### ISSUE TITLE
terminate_search() is returning HTTP Status 400 Bad Request

### ISSUE THREAD

**Issue by cmlh** [CSIRTAmericas/pyintelxio#1]
[terminate_search()](https://github.com/cmlh/pyintelxio/blob/main/pyintelx/pyintelx.py#L63) is returning `HTTP Status 400 Bad Request` as per the following syslog debug output (I've modified the `id` Query Parameter and API Key below):

```
DEBUG:terminate_search
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 3.intelx.io:443
send: b'GET /live/search/internal?id=00000000-0000-0000-0000-000000000000 HTTP/1.1\r\nHost: 3.intelx.io\r\nUser-Agent: IX-Python/0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nX-Key: 00000000-0000-0000-0000-000000000000\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
```
The command line of the above is both `pyintelx -search [domain] -limit 10 --identityenabled --accounts` and `pyintelx -search [domain] -limit 10 --identityenabled`

**Comment by Kleissner** [comment]
`/live/search/internal` always requires a selector. You would use that endpoint with `&terminate=[search ID]` and `selector=[selector]` parameters if you want to start a new search and use the &terminate= to terminate a previous one.

Use `/live/search/terminate` to only terminate a search, without starting a new one.

**Comment by feerbau** [comment]
@cmlh @Kleissner this shoud be fixed now.
