### ISSUE TITLE
NameError: name 'ix_identity' is not defined

### ISSUE THREAD

**Issue by cmlh** [CSIRTAmericas/pyintelxio#3]
If `$ export IDENTITY_ENABLED=` is not set then the following error is returned:

```bash
$ pyintelx -search example.com -limit 10 --identityenabled --accounts

     _____      _       ___   __
    |_   _|    | |     | \ \ / /
      | | _ __ | |_ ___| |\ V /
      | || '_ \| __/ _ \ |/   \
     _| || | | | ||  __/ / /^\ \
     \___/_| |_|\__\___|_\/   \/

       a command line client
           for intelx.io


Traceback (most recent call last):
  File "/venv/bin/pyintelx", line 242, in <module>
    ix_identity,
    ^^^^^^^^^^^
NameError: name 'ix_identity' is not defined

$
```
Can this be inserted into the [README file
](https://github.com/CSIRTAmericas/pyintelxio/blob/main/README.md) please  as it also occurs without `--accounts` command line flag too?

**Comment by feerbau** [comment]
Thanks for the feedback, we will fix this as soon as possible! @cmlh

**Comment by feerbau** [comment]
@cmlh this should be fixed now. Feel free to open new issues if there are any more problems or you have recommendations.
